name: OPItems
description: The OPItems Plugin
authors: [ cel20 ]
version: '1.12.0'

main: cel20.opitems.op.Main
api-version: '1.20.6'

commands:
  opitems:
    description: OPItems's main command
    usage: /opitems < help | cel20.gui | recipes | update | skull | upgradeItems>
  items:
    description: Lets you remove ALL loaded Items or gets the Amount of Items from all Players.
    usage: /cel20.items <remove | player_heap >

#Load After:
softdepend: [ Multiverse-Core ]

load: POSTWORLD

